services:
  nextcloud-ts:
    image: tailscale/tailscale:latest
    container_name: nas-nextcloud-ts
    hostname: nas-nextcloud
    environment:
      - TS_AUTHKEY=tskey-auth-k4A757N9tg11CNTRL-rVTXrGK2YjGShxAJ5ZWSjGc91c9zbRtb
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    volumes:
      - /volume1/docker/data/nextcloud/ts-config:/config
      - /volume1/docker/data/nextcloud/ts-state:/var/lib/tailscale
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nas-nextcloud
    network_mode: service:nextcloud-ts
    volumes:
      - /volume1/docker/data/nextcloud/data:/var/www/html/data
      - /volume1/docker/data/nextcloud/config:/var/www/html/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=REPLACE_ME
    depends_on:
      - nextcloud-db
    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.11
    container_name: nas-nextcloud-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACE_ME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=REPLACE_ME
    volumes:
      - /volume1/docker/data/nextcloud/database:/var/lib/mysql
    restart: unless-stopped